#ifndef RTW_HEADER_PV_Battery_Grid2021a_acc_types_h_
#define RTW_HEADER_PV_Battery_Grid2021a_acc_types_h_
typedef struct P_Subsystempi2delay_PV_Battery_Grid2021a_T_
P_Subsystempi2delay_PV_Battery_Grid2021a_T ; typedef struct
P_Subsystem1_PV_Battery_Grid2021a_T_ P_Subsystem1_PV_Battery_Grid2021a_T ;
typedef struct P_AutomaticGainControl_PV_Battery_Grid2021a_T_
P_AutomaticGainControl_PV_Battery_Grid2021a_T ; typedef struct
P_NegSeqComputation_PV_Battery_Grid2021a_T_
P_NegSeqComputation_PV_Battery_Grid2021a_T ; typedef struct
P_ZeroSeqComputation_PV_Battery_Grid2021a_T_
P_ZeroSeqComputation_PV_Battery_Grid2021a_T ; typedef struct
P_Subsystempi2delay_PV_Battery_Grid2021a_k_T_
P_Subsystempi2delay_PV_Battery_Grid2021a_k_T ; typedef struct
P_Subsystem1_PV_Battery_Grid2021a_j_T_ P_Subsystem1_PV_Battery_Grid2021a_j_T
; typedef struct P_PV_Battery_Grid2021a_T_ P_PV_Battery_Grid2021a_T ;
#endif
